In [1]:
# Memory Efficiency Example
import numpy as np
import sys

# Create a Python list and a NumPy array of same integers
py_list = list(range(1000))
np_array = np.arange(1000)

print("Memory used by Python list:", sys.getsizeof(py_list))
print("Memory used by NumPy array:", np_array.nbytes)

Memory used by Python list: 8056
Memory used by NumPy array: 4000


In [2]:
#Speed Efficiency Example
import time

# Create big list and array
size = 10_000_000
py_list = list(range(size))
np_array = np.arange(size)

# Multiply each element by 2 using list comprehension
start = time.time()
py_list = [x*2 for x in py_list]
end = time.time()
print("Python list time:", end-start)

# Multiply each element by 2 using vectorized NumPy
start = time.time()
np_array = np_array * 2
end = time.time()
print("NumPy array time:", end-start)

Python list time: 1.6457746028900146
NumPy array time: 0.04908275604248047


In [3]:
#Element-wise operation

# Python list
py_list1 = [1, 2, 3, 4, 5]
py_list2 = [6, 7, 8, 9, 10]

# NumPy arrays
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])

#LIST
# Elementwise addition (needs loop or comprehension)
list_add = [x + y for x, y in zip(py_list1, py_list2)]

# Scalar multiplication (needs loop)
list_mul = [x * 2 for x in py_list1]

# NUMPY
# Elementwise addition (one line)
np_add = np_arr1 + np_arr2

# Scalar multiplication (one line)
np_mul = np_arr1 * 2

print("List addition:", list_add)
print("NumPy addition:", np_add)

print("List scalar multiply:", list_mul)
print("NumPy scalar multiply:", np_mul)

List addition: [7, 9, 11, 13, 15]
NumPy addition: [ 7  9 11 13 15]
List scalar multiply: [2, 4, 6, 8, 10]
NumPy scalar multiply: [ 2  4  6  8 10]


In [4]:
# More NumPy richness
print("Dot product:", np.dot(np_arr1, np_arr2))    # Vector dot product
print("Square roots:", np.sqrt(np_arr1))           # Elementwise sqrt
print("Mean:", np.mean(np_arr1))                   # Average
 # @ => matrix multiplication operator(introduced in PEP 465, Python 3.5+  or use np.matmul() or np.dot()
print("Matrix multiplication:\n", np_arr1.reshape(5,1) @ np_arr2.reshape(1,5))


Dot product: 130
Square roots: [1.         1.41421356 1.73205081 2.         2.23606798]
Mean: 3.0
Matrix multiplication:
 [[ 6  7  8  9 10]
 [12 14 16 18 20]
 [18 21 24 27 30]
 [24 28 32 36 40]
 [30 35 40 45 50]]


In [5]:
# elementwise addtion using list variants 1
result = [py_list1[i] + py_list2[i] for i in range(len(py_list1))]
print(result)  

[7, 9, 11, 13, 15]


In [6]:
# elementwise addtion using list variants 2
result = [py_list1[i] + py_list2[i] for i, _ in enumerate(py_list1)]
print(result) 

[7, 9, 11, 13, 15]


In [7]:
# elementwise addtion using list variants 3
result = []
for i in range(len(py_list1)):
    result.append(py_list1[i] +py_list2[i])

print(result) 

[7, 9, 11, 13, 15]
